### ISSUE TITLE
How to get transmission map?

### ISSUE THREAD

**Issue by Ynqqq2022** [CV-Reimplementation/Ucolor-Reimplementation#1]
Thank you for your fantastic repository. I'd like to know how to generate transmission map? The author used GDCP to generate them. Do you have the code for GDCP? Could you share it with me via a file-sharing service or email? My email is [ynqqqqqq@gmail.com](mailto:ynqqqqqq@gmail.com). Thank you so much.

**Comment by xuhangc** [comment]
Hi, you can find the matlab code to generate transmission map in the author's repo [here](https://github.com/Li-Chongyi/Ucolor)
